// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dominio
{
    public partial class Cita
    {
        public Cita()
        {
            Atencion = new HashSet<Atencion>();
        }

        public DateTime? Fecha_Hora { get; set; }
        public string IDCita { get; set; }
        public string Descripcion { get; set; }
        public string IDVeterinario { get; set; }

        public virtual Veterinario IDVeterinarioNavigation { get; set; }
        public virtual ICollection<Atencion> Atencion { get; set; }
    }
}