// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dominio
{
    public partial class Detalles_Pedido
    {
        public string IDPedido { get; set; }
        public string IDProducto { get; set; }
        public int? Cantidad { get; set; }
        public double? Descuento { get; set; }
        public double? PrecioUnidad { get; set; }

        public virtual Pedido IDPedidoNavigation { get; set; }
        public virtual Producto IDProductoNavigation { get; set; }
    }
}