// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dominio
{
    public partial class HistoriaClinica
    {
        public HistoriaClinica()
        {
            Atencion = new HashSet<Atencion>();
        }

        public string IDHistoriaC { get; set; }
        public DateTime FechaRegistro { get; set; }
        public string Diagnostico { get; set; }
        public string Tratamiento { get; set; }
        public string Medicamentos { get; set; }
        public string Examenes { get; set; }

        public virtual ICollection<Atencion> Atencion { get; set; }
    }
}