// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dominio
{
    public partial class Mascota
    {
        public Mascota()
        {
            Atencion = new HashSet<Atencion>();
        }

        public string Nombre { get; set; }
        public string IDMascota { get; set; }
        public string Edad { get; set; }
        public string Raza { get; set; }
        public string Especie { get; set; }
        public string Sexo { get; set; }
        public string DNI { get; set; }
        public int? Peso { get; set; }

        public virtual Usuario DNINavigation { get; set; }
        public virtual ICollection<Atencion> Atencion { get; set; }
    }
}