// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dominio
{
    public partial class Pedido
    {
        public Pedido()
        {
            Detalles_Pedido = new HashSet<Detalles_Pedido>();
        }

        public string IDPedido { get; set; }
        public int? Cantidad { get; set; }
        public DateTime? FechaPedido { get; set; }
        public string DNI { get; set; }

        public virtual Usuario DNINavigation { get; set; }
        public virtual ICollection<Detalles_Pedido> Detalles_Pedido { get; set; }
    }
}