// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dominio
{
    public partial class Producto
    {
        public Producto()
        {
            Detalles_Pedido = new HashSet<Detalles_Pedido>();
        }

        public string IDProducto { get; set; }
        public string Nombre { get; set; }
        public int? UnidadStock { get; set; }
        public double? PrecioUnidad { get; set; }
        public string Categoria { get; set; }
        public string Marca { get; set; }

        public virtual ICollection<Detalles_Pedido> Detalles_Pedido { get; set; }
    }
}