// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dominio
{
    public partial class Veterinario
    {
        public Veterinario()
        {
            Cita = new HashSet<Cita>();
        }

        public string IDVeterinario { get; set; }
        public string Nombre { get; set; }
        public string ApellidoP { get; set; }
        public string ApellidoM { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string Especialidad { get; set; }
        public DateTime? FechaHora_Trabajo { get; set; }
        public int? Precio_Especialidad { get; set; }
        public string Descripcion { get; set; }

        public virtual ICollection<Cita> Cita { get; set; }
    }
}